package com.douglaswhitehead.model.digitaldata;

import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.junit.Test;
import org.skyscreamer.jsonassert.JSONAssert;

import com.douglaswhitehead.model.digitaldata.cart.CartImpl;
import com.douglaswhitehead.model.digitaldata.cart.PriceImpl;
import com.douglaswhitehead.model.digitaldata.common.AddressImpl;
import com.douglaswhitehead.model.digitaldata.common.AttributesImpl;
import com.douglaswhitehead.model.digitaldata.common.CategoryImpl;
import com.douglaswhitehead.model.digitaldata.common.ItemImpl;
import com.douglaswhitehead.model.digitaldata.component.ComponentImpl;
import com.douglaswhitehead.model.digitaldata.component.ComponentInfoImpl;
import com.douglaswhitehead.model.digitaldata.event.EventImpl;
import com.douglaswhitehead.model.digitaldata.event.EventInfoImpl;
import com.douglaswhitehead.model.digitaldata.page.PageImpl;
import com.douglaswhitehead.model.digitaldata.page.PageInfoImpl;
import com.douglaswhitehead.model.digitaldata.pageinstanceid.PageInstanceIDImpl;
import com.douglaswhitehead.model.digitaldata.privacy.AccessCategory;
import com.douglaswhitehead.model.digitaldata.privacy.AccessCategoryImpl;
import com.douglaswhitehead.model.digitaldata.privacy.PrivacyImpl;
import com.douglaswhitehead.model.digitaldata.product.ProductImpl;
import com.douglaswhitehead.model.digitaldata.product.ProductInfoImpl;
import com.douglaswhitehead.model.digitaldata.transaction.TotalImpl;
import com.douglaswhitehead.model.digitaldata.transaction.TransactionImpl;
import com.douglaswhitehead.model.digitaldata.user.ProfileImpl;
import com.douglaswhitehead.model.digitaldata.user.ProfileInfoImpl;
import com.douglaswhitehead.model.digitaldata.user.SegmentImpl;
import com.douglaswhitehead.model.digitaldata.user.SocialImpl;
import com.douglaswhitehead.model.digitaldata.user.UserImpl;
import com.douglaswhitehead.model.digitaldata.version.VersionImpl;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.ObjectMapper;

public class DigitalDataImplTest {
	
	private static final String VALID = "{\"version\":{\"version\":\"1.0\"},\"pageInstanceID\":{\"pageInstanceID\":\"homepage-01-production\"},\"transaction\":{\"attributes\":{},\"total\":{\"voucherCode\":\"Alpha\",\"voucherDiscount\":0.50,\"shippingMethod\":\"UPS\",\"priceWithTax\":205,\"transactionTotal\":215,\"basePrice\":350.00,\"currency\":\"EUR\",\"taxRate\":0.20,\"shipping\":10.00},\"transactionID\":\"ABC-123D\",\"item\":[{\"attributes\":{},\"category\":{\"primaryCategory\":\"Haircare\"},\"productInfo\":{\"security\":{\"productName\":[\"Analytics\"]},\"size\":\"250ml\",\"color\":\"black\",\"productName\":\"Propecia\",\"productURL\":\"http://site.com/p.html\",\"productImage\":\"http://site.com/pro250_large.png\",\"productThumbnail\":\"http://site.com/pro250_thumb.png\",\"manufacturer\":\"Pharma\",\"description\":\"Hair Regrowth\",\"productID\":\"pro2500\",\"sku\":\"DEF789-012G\"},\"linkedProduct\":[{\"productInfo\":{\"security\":{\"productName\":[\"Analytics\"]},\"size\":\"300ml\",\"color\":\"brown\",\"productName\":\"Rogaine\",\"productURL\":\"http://site.com/r.html\",\"productImage\":\"http://site.com/rog300_large.png\",\"productThumbnail\":\"http://site.com/rog300_thumb.png\",\"manufacturer\":\"Pharma\",\"description\":\"Hair Regrowth\",\"productID\":\"rog3000\",\"sku\":\"ABC123-456D\"}}],\"quantity\":1,\"price\":{\"voucherCode\":\"Alpha\",\"voucherDiscount\":0.50,\"shippingMethod\":\"UPS\",\"priceWithTax\":85,\"basePrice\":150.00,\"currency\":\"EUR\",\"taxRate\":0.20,\"shipping\":5.00}},{\"attributes\":{},\"category\":{\"primaryCategory\":\"Haircare\"},\"productInfo\":{\"security\":{\"productName\":[\"Analytics\"]},\"size\":\"300ml\",\"color\":\"brown\",\"productName\":\"Rogaine\",\"productURL\":\"http://site.com/r.html\",\"productImage\":\"http://site.com/rog300_large.png\",\"productThumbnail\":\"http://site.com/rog300_thumb.png\",\"manufacturer\":\"Pharma\",\"description\":\"Hair Regrowth\",\"productID\":\"rog3000\",\"sku\":\"ABC123-456D\"},\"linkedProduct\":[{\"productInfo\":{\"security\":{\"productName\":[\"Analytics\"]},\"size\":\"250ml\",\"color\":\"black\",\"productName\":\"Propecia\",\"productURL\":\"http://site.com/p.html\",\"productImage\":\"http://site.com/pro250_large.png\",\"productThumbnail\":\"http://site.com/pro250_thumb.png\",\"manufacturer\":\"Pharma\",\"description\":\"Hair Regrowth\",\"productID\":\"pro2500\",\"sku\":\"DEF789-012G\"}}],\"quantity\":1,\"price\":{\"voucherCode\":\"Alpha\",\"voucherDiscount\":0.50,\"shippingMethod\":\"UPS\",\"priceWithTax\":120,\"basePrice\":200.00,\"currency\":\"EUR\",\"taxRate\":0.20,\"shipping\":5.00}}],\"profile\":{\"address\":{\"security\":{\"line1\":[\"Analytics\"],\"line2\":[\"Analytics\"]},\"country\":\"test country\",\"stateProvince\":\"test state\",\"postalCode\":\"55555\",\"line1\":\"555 test street\",\"line2\":\"apt test\",\"city\":\"test town\"},\"attributes\":{},\"profileInfo\":{\"security\":{\"email\":[\"Analytics\"]},\"language\":\"en-US\",\"type\":\"customer\",\"returningStatus\":\"new\",\"userName\":\"me\",\"profileID\":\"humanbing12345\"},\"social\":{}}},\"page\":{\"attributes\":{},\"category\":{\"primaryCategory\":\"testCat\"},\"pageInfo\":{\"security\":{\"author\":[\"Analytics\"],\"publisher\":[\"Analytics\"]},\"language\":\"en-US\",\"variant\":\"2\",\"version\":\"1.01\",\"destinationURL\":\"http://www.test.com/search/results\",\"referringURL\":\"http://www.test.com/\",\"breadcrumbs\":[\"home\",\"search\",\"results\"],\"effectiveDate\":1052712000000,\"expiryDate\":1055390400000,\"industryCodes\":\"5140, 5141\",\"onsiteSearchTerm\":\"testing 123\",\"onsiteSearchResults\":5432,\"pageID\":\"testPageId-prod\",\"pageName\":\"testPageName\",\"sysEnv\":\"desktop\",\"author\":\"Test McGee\",\"issueDate\":1050120000000,\"geoRegion\":\"US\",\"publisher\":\"Shirley J Tester\"}},\"product\":[{\"attributes\":{},\"category\":{\"security\":{\"primaryCategory\":[\"Analytics\"]},\"primaryCategory\":\"Haircare\"},\"productInfo\":{\"security\":{\"productName\":[\"Analytics\"]},\"size\":\"300ml\",\"color\":\"brown\",\"productName\":\"Rogaine\",\"productURL\":\"http://site.com/r.html\",\"productImage\":\"http://site.com/rog300_large.png\",\"productThumbnail\":\"http://site.com/rog300_thumb.png\",\"manufacturer\":\"Pharma\",\"description\":\"Hair Regrowth\",\"productID\":\"rog3000\",\"sku\":\"ABC123-456D\"},\"linkedProduct\":[{},{}]}],\"cart\":{\"attributes\":{},\"price\":{\"voucherCode\":\"Alpha\",\"voucherDiscount\":0.50,\"shippingMethod\":\"UPS\",\"priceWithTax\":205,\"basePrice\":350.00,\"currency\":\"EUR\",\"taxRate\":0.20,\"shipping\":10.00,\"cartTotal\":215},\"cartID\":\"cart0001-Prod\",\"item\":[{\"attributes\":{},\"category\":{\"primaryCategory\":\"Haircare\"},\"productInfo\":{\"security\":{\"productName\":[\"Analytics\"]},\"size\":\"250ml\",\"color\":\"black\",\"productName\":\"Propecia\",\"productURL\":\"http://site.com/p.html\",\"productImage\":\"http://site.com/pro250_large.png\",\"productThumbnail\":\"http://site.com/pro250_thumb.png\",\"manufacturer\":\"Pharma\",\"description\":\"Hair Regrowth\",\"productID\":\"pro2500\",\"sku\":\"DEF789-012G\"},\"linkedProduct\":[{\"productInfo\":{\"security\":{\"productName\":[\"Analytics\"]},\"size\":\"300ml\",\"color\":\"brown\",\"productName\":\"Rogaine\",\"productURL\":\"http://site.com/r.html\",\"productImage\":\"http://site.com/rog300_large.png\",\"productThumbnail\":\"http://site.com/rog300_thumb.png\",\"manufacturer\":\"Pharma\",\"description\":\"Hair Regrowth\",\"productID\":\"rog3000\",\"sku\":\"ABC123-456D\"}}],\"quantity\":1,\"price\":{\"voucherCode\":\"Alpha\",\"voucherDiscount\":0.50,\"shippingMethod\":\"UPS\",\"priceWithTax\":85,\"basePrice\":150.00,\"currency\":\"EUR\",\"taxRate\":0.20,\"shipping\":5.00}},{\"attributes\":{},\"category\":{\"primaryCategory\":\"Haircare\"},\"productInfo\":{\"security\":{\"productName\":[\"Analytics\"]},\"size\":\"300ml\",\"color\":\"brown\",\"productName\":\"Rogaine\",\"productURL\":\"http://site.com/r.html\",\"productImage\":\"http://site.com/rog300_large.png\",\"productThumbnail\":\"http://site.com/rog300_thumb.png\",\"manufacturer\":\"Pharma\",\"description\":\"Hair Regrowth\",\"productID\":\"rog3000\",\"sku\":\"ABC123-456D\"},\"linkedProduct\":[{\"productInfo\":{\"security\":{\"productName\":[\"Analytics\"]},\"size\":\"250ml\",\"color\":\"black\",\"productName\":\"Propecia\",\"productURL\":\"http://site.com/p.html\",\"productImage\":\"http://site.com/pro250_large.png\",\"productThumbnail\":\"http://site.com/pro250_thumb.png\",\"manufacturer\":\"Pharma\",\"description\":\"Hair Regrowth\",\"productID\":\"pro2500\",\"sku\":\"DEF789-012G\"}}],\"quantity\":1,\"price\":{\"voucherCode\":\"Alpha\",\"voucherDiscount\":0.50,\"shippingMethod\":\"UPS\",\"priceWithTax\":120,\"basePrice\":200.00,\"currency\":\"EUR\",\"taxRate\":0.20,\"shipping\":5.00}}]},\"event\":[{\"attributes\":{},\"category\":{\"security\":{\"primaryCategory\":[\"Analytics\"]},\"primaryCategory\":\"testCat\"},\"eventInfo\":{\"cause\":\"add portal 1234 button clicked\",\"type\":\"contentModifier\",\"timestamp\":1444349360457,\"eventAction\":\"addportal\",\"eventPoints\":200,\"eventName\":\"Add News Portal\",\"effect\":\"include portal 1234\"}}],\"component\":[{\"attributes\":{},\"category\":{\"primaryCategory\":\"testCat\"},\"componentInfo\":{\"security\":{\"componentID\":[\"Analytics\"]},\"componentID\":\"rog300v\"}}],\"user\":[{\"profile\":[{\"address\":{\"security\":{\"line1\":[\"Analytics\"],\"line2\":[\"Analytics\"]},\"country\":\"test country\",\"stateProvince\":\"test state\",\"postalCode\":\"55555\",\"line1\":\"555 test street\",\"line2\":\"apt test\",\"city\":\"test town\"},\"attributes\":{},\"profileInfo\":{\"security\":{\"email\":[\"Analytics\"]},\"language\":\"en-US\",\"type\":\"customer\",\"returningStatus\":\"new\",\"userName\":\"me\",\"profileID\":\"humanbing12345\",\"email\":\"me@test.com\"},\"social\":{}}],\"segment\":{}}],\"privacy\":{\"accessCategories\":[{\"categoryName\":\"Analytics\",\"domains\":[\"*\"]},{\"categoryName\":\"Default\",\"domains\":[\"*\"]}]}}";
	
	@Test
	public void test() throws Exception {
		
		SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyy");
		Date issueDate = simpleDateFormat.parse("12/28/2001");
		Date effectiveDate = simpleDateFormat.parse("12/29/2001");
		Date expiryDate = simpleDateFormat.parse("12/30/2001");
		
		DigitalData object = new DigitalDataImpl.Builder()
									.pageInstanceID(new PageInstanceIDImpl.Builder()
															.pageInstanceID("homepage-01-production")
														.build())
									.page(new PageImpl.Builder()
											.pageInfo(new PageInfoImpl.Builder()
													.pageID("testPageId-prod")
													.pageName("testPageName")
													.destinationURL("http://www.test.com/search/results")
													.referringURL("http://www.test.com/")
													.sysEnv("desktop")
													.variant("2")
													.version("1.01")
													.breadcrumbs(new String[]{"home", "search", "results"})
													.author("Test McGee").security(new String[]{"Analytics"})
													.issueDate(issueDate)
													.effectiveDate(effectiveDate)
													.expiryDate(expiryDate)
													.language("en-US")
													.geoRegion("US")
													.industryCodes("5140, 5141")
													.publisher("Shirley J Tester").security(new String[]{"Analytics"})
													.onsiteSearchTerm("testing 123")
													.onsiteSearchResults(Long.valueOf(5432))
												.build())
											.category(new CategoryImpl.Builder()
																.primaryCategory("testCat")
															.build())
											.attributes(new AttributesImpl.Builder().build())
										.build())
									.product(new ProductImpl[]{new ProductImpl.Builder()
											.productInfo(new ProductInfoImpl.Builder()
													.productID("rog3000")
													.productName("Rogaine").security(new String[]{"Analytics"})
													.description("Hair Regrowth")
													.productURL("http://site.com/r.html")
													.productImage("http://site.com/rog300_large.png")
													.productThumbnail("http://site.com/rog300_thumb.png")
													.manufacturer("Pharma")
													.sku("ABC123-456D")
													.color("brown")
													.size("300ml")
												.build())
											.category(new CategoryImpl.Builder()
													.primaryCategory("Haircare").security(new String[]{"Analytics"})
												.build())
											.linkedProduct(new ProductImpl[]{new ProductImpl.Builder().build(), new ProductImpl.Builder().build()})
											.attributes(new AttributesImpl.Builder().build())
										.build()})
									.cart(new CartImpl.Builder()
											.cartID("cart0001-Prod")
											.price(new PriceImpl.Builder()
													.basePrice(new BigDecimal("350.00"))
													.voucherCode("Alpha")
													.voucherDiscount(new BigDecimal("0.50"))
													.currency("EUR")
													.taxRate(new BigDecimal("0.20"))
													.shipping(new BigDecimal("10.00"))
													.shippingMethod("UPS")
													.priceWithTax(new BigDecimal("205"))
													.cartTotal(new BigDecimal("215"))
												.build())
											.attributes(new AttributesImpl.Builder().build())
											.item(new ItemImpl[]{
													new ItemImpl.Builder()
														.productInfo(new ProductInfoImpl.Builder()
																.productID("pro2500")
																.productName("Propecia").security(new String[]{"Analytics"})
																.description("Hair Regrowth")
																.productURL("http://site.com/p.html")
																.productImage("http://site.com/pro250_large.png")
																.productThumbnail("http://site.com/pro250_thumb.png")
																.manufacturer("Pharma")
																.sku("DEF789-012G")
																.color("black")
																.size("250ml")
															.build())
														.category(new CategoryImpl.Builder()
																.primaryCategory("Haircare")
															.build())
														.quantity(1)
														.price(new PriceImpl.Builder()
																.basePrice(new BigDecimal("150.00"))
																.voucherCode("Alpha")
																.voucherDiscount(new BigDecimal("0.50"))
																.currency("EUR")
																.taxRate(new BigDecimal("0.20"))
																.shipping(new BigDecimal("5.00"))
																.shippingMethod("UPS")
																.priceWithTax(new BigDecimal("85"))
																//.cartTotal(new BigDecimal("90")) // shouldn't use cartTotal on items in a cart
															.build())
														.linkedProduct(new ProductImpl[]{
																new ProductImpl.Builder()
																	.productInfo(new ProductInfoImpl.Builder()
																			.productID("rog3000")
																			.productName("Rogaine").security(new String[]{"Analytics"})
																			.description("Hair Regrowth")
																			.productURL("http://site.com/r.html")
																			.productImage("http://site.com/rog300_large.png")
																			.productThumbnail("http://site.com/rog300_thumb.png")
																			.manufacturer("Pharma")
																			.sku("ABC123-456D")
																			.color("brown")
																			.size("300ml")
																		.build())
																	.build()
																})
														.attributes(new AttributesImpl.Builder().build())
													.build(),
												new ItemImpl.Builder()
													.productInfo(new ProductInfoImpl.Builder()
															.productID("rog3000")
															.productName("Rogaine").security(new String[]{"Analytics"})
															.description("Hair Regrowth")
															.productURL("http://site.com/r.html")
															.productImage("http://site.com/rog300_large.png")
															.productThumbnail("http://site.com/rog300_thumb.png")
															.manufacturer("Pharma")
															.sku("ABC123-456D")
															.color("brown")
															.size("300ml")
														.build())
													.category(new CategoryImpl.Builder()
															.primaryCategory("Haircare")
														.build())
													.quantity(1)
													.price(new PriceImpl.Builder()
															.basePrice(new BigDecimal("200.00"))
															.voucherCode("Alpha")
															.voucherDiscount(new BigDecimal("0.50"))
															.currency("EUR")
															.taxRate(new BigDecimal("0.20"))
															.shipping(new BigDecimal("5.00"))
															.shippingMethod("UPS")
															.priceWithTax(new BigDecimal("120"))
															//.cartTotal(new BigDecimal("125")) // shouldn't use cartTotal on items in a cart
														.build())
													.linkedProduct(new ProductImpl[]{
															new ProductImpl.Builder()
																	.productInfo(new ProductInfoImpl.Builder()
																			.productID("pro2500")
																			.productName("Propecia").security(new String[]{"Analytics"})
																			.description("Hair Regrowth")
																			.productURL("http://site.com/p.html")
																			.productImage("http://site.com/pro250_large.png")
																			.productThumbnail("http://site.com/pro250_thumb.png")
																			.manufacturer("Pharma")
																			.sku("DEF789-012G")
																			.color("black")
																			.size("250ml")
																		.build())
																.build()
															})
													.attributes(new AttributesImpl.Builder().build())
												.build()
											})
										.build())
									.transaction(new TransactionImpl.Builder()
											.transactionID("ABC-123D")
											.profile(new ProfileImpl.Builder()
													.profileInfo(new ProfileInfoImpl.Builder()
															.profileID("humanbing12345")
															.userName("me")
															.email(null).security(new String[]{"Analytics"})
															.language("en-US")
															.returningStatus("new")
															.type("customer")
														.build())
													.address(new AddressImpl.Builder()
																.line1("555 test street").security(new String[]{"Analytics"})
																.line2("apt test").security(new String[]{"Analytics"})
																.city("test town")
																.stateProvince("test state")
																.postalCode("55555")
																.country("test country")
															.build())
													.social(new SocialImpl.Builder().build())
													.attributes(new AttributesImpl.Builder().build())
												.build())
											.total(new TotalImpl.Builder()
													.basePrice(new BigDecimal("350.00"))
													.voucherCode("Alpha")
													.voucherDiscount(new BigDecimal("0.50"))
													.currency("EUR")
													.taxRate(new BigDecimal("0.20"))
													.shipping(new BigDecimal("10.00"))
													.shippingMethod("UPS")
													.priceWithTax(new BigDecimal("205"))
													.transactionTotal(new BigDecimal("215"))
												.build())
											.attributes(new AttributesImpl.Builder().build())
											.item(new ItemImpl[]{
													new ItemImpl.Builder()
															.productInfo(new ProductInfoImpl.Builder()
																	.productID("pro2500")
																	.productName("Propecia").security(new String[]{"Analytics"})
																	.description("Hair Regrowth")
																	.productURL("http://site.com/p.html")
																	.productImage("http://site.com/pro250_large.png")
																	.productThumbnail("http://site.com/pro250_thumb.png")
																	.manufacturer("Pharma")
																	.sku("DEF789-012G")
																	.color("black")
																	.size("250ml")
																.build())
															.category(new CategoryImpl.Builder()
																	.primaryCategory("Haircare")
																.build())
															.quantity(1)
															.price(new PriceImpl.Builder()
																	.basePrice(new BigDecimal("150.00"))
																	.voucherCode("Alpha")
																	.voucherDiscount(new BigDecimal("0.50"))
																	.currency("EUR")
																	.taxRate(new BigDecimal("0.20"))
																	.shipping(new BigDecimal("5.00"))
																	.shippingMethod("UPS")
																	.priceWithTax(new BigDecimal("85"))
																	//.cartTotal(new BigDecimal("90")) // shouldn't use cartTotal on items in a transaction
																.build())
															.linkedProduct(new ProductImpl[]{
																	new ProductImpl.Builder()
																		.productInfo(new ProductInfoImpl.Builder()
																				.productID("rog3000")
																				.productName("Rogaine").security(new String[]{"Analytics"})
																				.description("Hair Regrowth")
																				.productURL("http://site.com/r.html")
																				.productImage("http://site.com/rog300_large.png")
																				.productThumbnail("http://site.com/rog300_thumb.png")
																				.manufacturer("Pharma")
																				.sku("ABC123-456D")
																				.color("brown")
																				.size("300ml")
																			.build())
																		.build()
																	})
															.attributes(new AttributesImpl.Builder().build())
														.build(),
													new ItemImpl.Builder()
														.productInfo(new ProductInfoImpl.Builder()
																.productID("rog3000")
																.productName("Rogaine").security(new String[]{"Analytics"})
																.description("Hair Regrowth")
																.productURL("http://site.com/r.html")
																.productImage("http://site.com/rog300_large.png")
																.productThumbnail("http://site.com/rog300_thumb.png")
																.manufacturer("Pharma")
																.sku("ABC123-456D")
																.color("brown")
																.size("300ml")
															.build())
														.category(new CategoryImpl.Builder()
																.primaryCategory("Haircare")
															.build())
														.quantity(1)
														.price(new PriceImpl.Builder()
																.basePrice(new BigDecimal("200.00"))
																.voucherCode("Alpha")
																.voucherDiscount(new BigDecimal("0.50"))
																.currency("EUR")
																.taxRate(new BigDecimal("0.20"))
																.shipping(new BigDecimal("5.00"))
																.shippingMethod("UPS")
																.priceWithTax(new BigDecimal("120"))
																//.cartTotal(new BigDecimal("125")) // shouldn't use cartTotal on items in a transaction
															.build())
														.linkedProduct(new ProductImpl[]{
																new ProductImpl.Builder()
																		.productInfo(new ProductInfoImpl.Builder()
																				.productID("pro2500")
																				.productName("Propecia").security(new String[]{"Analytics"})
																				.description("Hair Regrowth")
																				.productURL("http://site.com/p.html")
																				.productImage("http://site.com/pro250_large.png")
																				.productThumbnail("http://site.com/pro250_thumb.png")
																				.manufacturer("Pharma")
																				.sku("DEF789-012G")
																				.color("black")
																				.size("250ml")
																			.build())
																	.build()
																})
														.attributes(new AttributesImpl.Builder().build())
													.build()
												})
										.build())
									.event(new EventImpl[]{new EventImpl.Builder()
											.eventInfo(new EventInfoImpl.Builder()
													.eventName("Add News Portal")
													.eventAction("addportal")
													.eventPoints(200)
													.type("contentModifier")
													.timestamp(new Date(Long.valueOf("1444349360457")))
													.cause("add portal 1234 button clicked")
													.effect("include portal 1234")
												.build())
											.category(new CategoryImpl.Builder()
													.primaryCategory("testCat").security(new String[]{"Analytics"})
												.build())
											.attributes(new AttributesImpl.Builder()
												.build())
										.build()})
									.component(new ComponentImpl[]{new ComponentImpl.Builder()
											.componentInfo(new ComponentInfoImpl.Builder()
													.componentID("rog300v").security(new String[]{"Analytics"})
												.build())
											.category(new CategoryImpl.Builder()
													.primaryCategory("testCat")
												.build())
											.attributes(new AttributesImpl.Builder().build())
										.build()})
									.user(new UserImpl[]{new UserImpl.Builder()
											.segment(new SegmentImpl.Builder().build())
											.profile(new ProfileImpl[]{
													new ProfileImpl.Builder()
														.profileInfo(new ProfileInfoImpl.Builder()
																		.profileID("humanbing12345")
																		.userName("me")
																		.email("me@test.com").security(new String[]{"Analytics"})
																		.language("en-US")
																		.returningStatus("new")
																		.type("customer")
																	.build())
														.address(new AddressImpl.Builder()
																	.line1("555 test street").security(new String[]{"Analytics"})
																	.line2("apt test").security(new String[]{"Analytics"})
																	.city("test town")
																	.stateProvince("test state")
																	.postalCode("55555")
																	.country("test country")
																.build())
														.social(new SocialImpl.Builder().build())
														.attributes(new AttributesImpl.Builder().build())
													.build()
												})
										.build()})
									.privacy(new PrivacyImpl.Builder()
												.accessCategories(new AccessCategory[]{new AccessCategoryImpl.Builder()
																			.categoryName("Analytics")
																			.domains(new String[]{"*"})
																		.build()})
										.build())
									.version(new VersionImpl.Builder()
											.version("1.0")
										.build())
								.build();
		
		ObjectMapper mapper = new ObjectMapper();
		mapper.setSerializationInclusion(Include.NON_NULL);
		String output = mapper.writeValueAsString(object);
		
		System.out.println(VALID);
		System.out.println(output);
		
		JSONAssert.assertEquals(VALID, output, false);
		
	}

}
